# Generated by Django 4.0.5 on 2023-11-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watermarkedvideo',
            name='padding',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='watermarkedvideo',
            name='watermark_size',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
