# Generated by Django 4.0.5 on 2023-11-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract_audio', '0002_alter_audioextraction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioextraction',
            name='video',
        ),
        migrations.AddField(
            model_name='audioextraction',
            name='audio_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audioextraction',
            name='audio',
            field=models.FileField(null=True, upload_to='audios/'),
        ),
    ]
